server:
  port: 8083

spring:
  datasource:
    url: jdbc:hsqldb:mem:personaldb
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
