server:
  port: 8083

spring:
  datasource:
    url: jdbc:hsqldb:file:./data/personaldb;shutdown=true;hsqldb.lock_file=false
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
