server:
  port: 8083

spring:
  datasource:
    url: jdbc:hsqldb:mem:personaldb
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
