server:
  port: 8090

spring:
  datasource:
    url: jdbc:hsqldb:mem:pedidosdb
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
